name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-18
          override: true
      - run: rustup default nightly-2022-11-18
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  test-all-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-18
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-18
          components: llvm-tools-preview
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Coverage Tooling
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-llvm-cov
      - name: Run Coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --all-features --workspace --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          files: lcov.info
          fail_ci_if_error: true

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-18
          components: rustfmt
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-18
          components: clippy
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
